### ISSUE TITLE
Color Sensor Holder

### ISSUE THREAD

**Issue by Eiim** [olentangyfrc/InfiniteRecharge-2020#11]
For TCS3200. Will add details later.

**Comment by mrbbking** [comment]
Ours are as purchased from https://www.digikey.com/product-detail/en/dfrobot/SEN0101/1738-1035-ND/6588457

Data Sheet: https://media.digikey.com/pdf/Data%20Sheets/DFRobot%20PDFs/SEN0101_Web.pdf

**Comment by Eiim** [comment]
Mount is to be attached to a flat surface.
