### ISSUE TITLE
Attach SB50 Connector to KOP Battery

### ISSUE THREAD

**Issue by mrbbking** [olentangyfrc/InfiniteRecharge-2020#19]
Battery and SB50 w/ crimped ends are in the KOP box. This is the gray battery we're calling "Whoop-de-doo"

**Comment by MarsRaccoon** [comment]
Put connector on, leave open for now, waiting on proper heat shrink to come in.

**Comment by mrbbking** [comment]
changed title from doing the KOP battery connections to heatshrinking all batteries.
