### ISSUE TITLE
Create Button Box (Aux Box)

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/InfiniteRecharge-2020#28]
Developing a button box for testing purposes only as an aux driver control box.

**Comment by mrbbking** [comment]
top panel has 2 coats of polyurethane: should be ready to assemble Sat jan 18.
@sydneylewis22 and @isabellebubnick worked w/ drive to decide on layout last week.

**Comment by mrbbking** [comment]
Top is assembled and wired. Dimensions are determined for the rest of the box. I'm told those pieces are ready or close to ready. Let's get those and get this box assembled and tested with a drive station this weekend.

**Comment by mrbbking** [comment]
Only step left is to attach the USB panel mount when that arrives, then hook up to a Drive Station to test.
