### ISSUE TITLE
Build electrical components for mec sled 3

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/InfiniteRecharge-2020#7]
Need to assign others to this as well, but just getting things off my list into Git right now.

**Comment by MarsRaccoon** [comment]
Took elevator off of old Proto, only mech sled we have, Tomorrow will be making an electrical board and getting it online, this will be a good way to teach about the electronics on the robots

**Comment by MarsRaccoon** [comment]
Finished Demo, Tomorrow we should finish adding the CIM motors.
I talked with Schmidt and he said we might skip the actual electronics and use the sled for prototyping only. this is to leave room for the intake and shooter systems, as the electronics sometimes get in the way

**Comment by MarsRaccoon** [comment]
Ready to be Closed

**Comment by mrbbking** [comment]
I'm told this is no longer a priority, @olentangyfrcowner - can you confirm so we can close it?

**Comment by mrbbking** [comment]
Closing
